### ISSUE TITLE
Clarification for the #between? method

### ISSUE THREAD

**Issue by alleyben** [learn-co-curriculum/ttt-7-valid-move#14] opened 2016-03-27 00:32 UTC
The use and syntax of the #between? method in this lab is clear, but it is not clear if it is inclusive or exclusive i.e. its semantics. If we use the variable "number" to query number.between?(1, 3), are the integers 1 and 3 also included in the acceptable numbers? In other words is it the case that the method would apply to x such that 1 <= x >= 3 or if the method would apply to x such that 1 < x < 3 only? I use the terms "inclusive" for the former example and "exclusive" for the latter example though I don't know if that is the proper terminology. (Sorry, philosophy major here.) Upon further searching, I found that it's inclusive, but explicitly stating this in the lab would help greatly with its clarity.

**Comment by mendelB** [comment] 2016-04-14 15:25
@modalfish Thanks so much for this submission!  = and for waxing philosophical :)
The goal here is for the student to research the method on their own and reach the same conclusion that you did. So we're ambiguous about it here by design.
I'm going to go ahead and close this issue. Thanks again!!

**Closed as completed by mendelB** 2016-04-14 15:25 UTC
